name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node:
          - 20
          - 22
          - 24

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      # windows-latest (windows-2025) doesn't have a D: drive.
      #   So running tests on windows is _very_ slow withotu a Dev Drive
      # https://github.com/actions/runner-images/issues/12647
      # https://github.com/samypr100/setup-dev-drive/tree/main
      - uses: samypr100/setup-dev-drive@v3
        if: '"${{matrix.os}}" == "windows-latest"'
        with:
          mount-if-exists: true
          drive-type: Fixed
          env-mapping: |
            TEMP,{{ DEV_DRIVE }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
